export const API_CALLS_IN_PROGRESS = {
    BEGIN_CALL: 'API BEGIN CALL',
    CALL_ERROR: 'API CALL ERROR'
};

const LIST_CHARACTERS = {
    LOAD: 'LIST_CHARACTERS_LOAD',
    LOAD_SUCCESS: 'LIST_CHARACTERS_LOAD_SUCCESS',
    LOAD_FAIL: 'LIST_CHARACTERS_LOAD_FAIL',
};

const DETAILS_CHARACTER = {
    LOAD: 'DETAILS_CHARACTER_LOAD',
    LOAD_SUCCESS: 'DETAILS_CHARACTER_LOAD_SUCCESS',
    LOAD_FAIL: 'DETAILS_CHARACTER_LOAD_FAIL',
};

export { LIST_CHARACTERS, DETAILS_CHARACTER };
